SCREEN_WIDTH = 720
SCREEN_HEIGHT = 720

ROAD_WIDTH = 48
ROAD_HEIGHT = 48

CAR_HEIGHT = 40
CAR_WIDTH = 40

SCALE_FACTOR_Y = SCREEN_WIDTH // ROAD_WIDTH
SCALE_FACTOR_X = SCREEN_HEIGHT // ROAD_HEIGHT

MOVE_LEFT = (-1, 0)
MOVE_RIGHT = (1, 0)
MOVE_UP = (0, -1)
MOVE_DOWN = (0, 1)

CAR_SPRITE_LOCATION = "sprites/cars/car%d.png"
CAR_SPRITE_COUNT = 7

ROADMAP_LOCATION = "sprites/roadmap"
ROAD_SPRITE_LOCATION = "sprites/roadTexture_%03d.png"
ROAD_SPRITE_OFFSET = 1
ROAD_SPRITE_COUNT = 20
ROAD_COLORKEY = (33, 191, 143)

BACKGROUND_SPRITE_LOCATION = "sprites/background%02d.png"
BACKGROUND_SPRITE_COUNT = 3

INNER_LAYERS = [8]
AGENT_COUNT = 200

KEYPRESS_INTERVAL_MS = 24
FLUSH_INTERVAL_MS = 200
TARGET_FPS = 60

CAR_ACCELERATION_PERCEN = 1.10
CAR_DECELERATION_PERCEN = 0.90
CAR_ROTATION_DELTA = 8
CAR_MAXSPEED = 4

CROSSOVER_GENE_COUNT = 0
CARRYOVER_PARENT_COUNT = 2
USE_UNIFORM_CROSSOVER = False
MUTATION_PROBABILITY = 0.1
PARENT_SELECTION_COUNT = 5
USE_UNIQUE_PARENTS = True

AGENT_ALIVE_WEIGHT = 0.5
